"""Optimization and residual numerical kernels."""

from rietveld_next.optimization.diagnostics import (
    LabeledMatrix,
    correlation_matrix_from_covariance,
    covariance_from_jacobian as dense_covariance_from_jacobian,
    labeled_correlation_matrix_from_covariance,
    parameter_error_metrics,
)
from rietveld_next.optimization.global_search import (
    DifferentialEvolutionOptions,
    MultiStartOptions,
    MultiStartReport,
    PlaceholderReport,
    SimulatedAnnealingOptions,
    bayesian_optimization_placeholder,
    differential_evolution_minimize,
    mcmc_uncertainty_placeholder,
    multi_start_minimize,
    simulated_annealing_minimize,
)
from rietveld_next.optimization.jacobian import (
    GradientCheckResult,
    SparseJacobian,
    SparseJacobianEntry,
    finite_difference_jacobian,
    gradient_check,
    polynomial_background_residual_jacobian,
    scale_residual_derivative,
)
from rietveld_next.optimization.local import (
    ConvergenceReport,
    LocalOptimizerOptions,
    OptimizerSnapshot,
    coordinate_search_minimize,
)
from rietveld_next.optimization.objectives import (
    ObjectiveEvaluation,
    ObjectiveFunction,
    ObjectiveRegistry,
    ObjectiveSpec,
    built_in_objective,
    default_objective_registry,
    invalid_model_evaluation,
    least_squares_evaluation,
    poisson_deviance_evaluation,
)
from rietveld_next.optimization.residuals import residual_vector
from rietveld_next.optimization.transforms import (
    BoundTransform,
    ParameterScale,
    scale_parameters,
    unscale_parameters,
)
from rietveld_next.optimization.uncertainty import (
    CorrelationDiagnostics,
    CovarianceDiagnostics,
    HighCorrelation,
    correlation_from_covariance,
    covariance_from_jacobian,
    covariance_from_normal_matrix,
)

__all__ = [
    "BoundTransform",
    "CorrelationDiagnostics",
    "ConvergenceReport",
    "CovarianceDiagnostics",
    "DifferentialEvolutionOptions",
    "GradientCheckResult",
    "HighCorrelation",
    "LocalOptimizerOptions",
    "LabeledMatrix",
    "MultiStartOptions",
    "MultiStartReport",
    "ObjectiveEvaluation",
    "ObjectiveFunction",
    "ObjectiveRegistry",
    "ObjectiveSpec",
    "OptimizerSnapshot",
    "ParameterScale",
    "PlaceholderReport",
    "SimulatedAnnealingOptions",
    "SparseJacobian",
    "SparseJacobianEntry",
    "bayesian_optimization_placeholder",
    "built_in_objective",
    "coordinate_search_minimize",
    "correlation_from_covariance",
    "correlation_matrix_from_covariance",
    "covariance_from_normal_matrix",
    "covariance_from_jacobian",
    "dense_covariance_from_jacobian",
    "differential_evolution_minimize",
    "default_objective_registry",
    "finite_difference_jacobian",
    "gradient_check",
    "invalid_model_evaluation",
    "labeled_correlation_matrix_from_covariance",
    "least_squares_evaluation",
    "mcmc_uncertainty_placeholder",
    "multi_start_minimize",
    "parameter_error_metrics",
    "poisson_deviance_evaluation",
    "polynomial_background_residual_jacobian",
    "residual_vector",
    "scale_residual_derivative",
    "scale_parameters",
    "simulated_annealing_minimize",
    "unscale_parameters",
]
